
object DependenciesVersions {

    const val kotlinVersion = "1.5.10"
    const val kotlinKtxVersion = "1.6.0"
    const val appCompatVersion = "1.3.1"
    const val googleMaterialVersion = "1.4.0"
    const val constraintLayoutVersion ="2.1.0"
    const val navigationComponentVersion = "2.3.3"
    const val hiltVersion = "2.33-beta"
    const val retrofitVersion = "2.9.0"
    const val roomVersion = "2.3.0"
    const val coroutinesVersion = "1.4.3"
    const val workManagerVersion = "2.5.0"
    const val glideVersion = "4.11.0"
    const val settingsVersion = "1.1.1"
    const val chartsVersion = "3.1.0"
    const val rssParserVersion = "3.1.4"
    const val shimmmerVersion = "0.5.0"
    const val junitTestVersion = "1.1.3"
    const val espressoVersion = "3.3.0"